# Generated by Django 5.1.6 on 2025-02-14 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_delete_admin_alter_review_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='loyaltyprogram',
            name='user',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.RemoveField(
            model_name='review',
            name='vehicle',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='LoyaltyProgram',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
