# Generated by Django 5.1.6 on 2025-02-14 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0008_remove_vehicle_air_conditioning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='child_seat',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='gps',
        ),
    ]
