# Generated by Django 5.1.6 on 2025-02-14 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0009_remove_vehicle_child_seat_remove_vehicle_gps'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminProfile',
        ),
    ]
